oscar-system/libsingular-julia

- CMakeLists.txt
- build.jl
which is not perfect (I don;t know what the conventions are)
but it illustrates what to do
> "fix" CmakeFile and add a build.jl

- coeffs.cpp
... it is identical to n_Delete
See also https://github.com/oscar-system/Singular.jl/pull/347
> Remove n_Delete_Q

- coeffs.cpp
... by letting it return its result, instead of void.
> Make n_InpMult actually useful

- coeffs.cpp
- rings.cpp
These are needed to recognize the rings from singular.
> more functions for ring identification

- caller.cpp
Added a first try on conversion of Singular.jl arrays to Singular lists in order to be able to call more Singular libraries in Singular.jl
> First try on conversion of Singular.jl arrays to Singular lists

- coeffs.cpp
- rings.cpp
Would like @hannes14 to have a look at this before merging. It seems to work and is almost verbatim from the singular source code, but I don't know what I could have messed up here. I couldn't find a function for doing this in the kernel - maybe it is time for such a function?
> getting and setting the minpoly

- .github/workflows/oscar.yml
- OscarCI.toml
~~This branch currently includes #17 but that can be changed as needed.~~ _edit: not anymore, rebased onto master_
> downstream testing using OscarCI / OscarDevTools

- ideals.cpp
for ideal*poly
and does intersection(ideal...)
> add ideal version of mp_MultP

- coeffs.cpp
goes with https://github.com/oscar-system/Singular.jl/pull/427
> fix transExt_to_poly nullptr

- singular.cpp
goes with https://github.com/oscar-system/Singular.jl/pull/426
subsumes https://github.com/oscar-system/libsingular-julia/pull/28
> reset errorreported + use singular_error + tweaks

- coeffs.cpp
goes with https://github.com/oscar-system/Singular.jl/pull/428
> n_algExt -> n_transExt conversion

- coeffs.cpp
goes with https://github.com/oscar-system/Singular.jl/pull/421
> proper num/den and gcdx + normalize for QQ

- rings.cpp
- singular.cpp
goes with https://github.com/oscar-system/Singular.jl/pull/418
> add some functions for communicating orderings

- ideals.cpp
goes with: https://github.com/oscar-system/Singular.jl/pull/435
> add scDimIntRing

- caller.cpp
goes with https://github.com/oscar-system/Singular.jl/pull/443
> missing matrix cmds

- coeffs.cpp
goes with https://github.com/oscar-system/Singular.jl/pull/457
> transExt_to_algExt conversion

- ideals.cpp
- rings.cpp
goes with https://github.com/oscar-system/Singular.jl/pull/458
> add second lift and a correct gcdx

- ideals.cpp
to introduce interreduce to Singular.jl
> add id_InterRed

- ideals.cpp
goes with https://github.com/oscar-system/Singular.jl/pull/493
> singular's degree and mult commands

- singular.cpp
resolves https://github.com/oscar-system/Singular.jl/issues/507
> don't always write to stderr

- ideals.cpp
goes with https://github.com/oscar-system/Singular.jl/pull/547
> add two arg kbase

- ideals.cpp
- rings.cpp
goes with https://github.com/oscar-system/Singular.jl/pull/575
> add homogeneous functions

- caller.cpp
see crash in https://github.com/oscar-system/Singular.jl/issues/595
> copy ring content pointers

- matrices.cpp
iinterface to Singulars "n-th exterior power of a matrix"
> access to mp_Wedge
